name: publish-upm

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ./.github/workflows/sync-package.yml
      - uses: actions/checkout@v2
      - name: publish
        run: |
          git tag upm/${{ github.event.inputs.tag_name }}
          git push